collections:
  - name: ansible.posix
  - name: ansible.windows
  - name: ansible.utils
  - name: chocolatey.chocolatey
  - name: community.aws
  - name: community.azure
  - name: community.crypto
  - name: community.dns
  - name: community.docker
  - name: community.fortios
  - name: community.general
  - name: community.google
  - name: community.hashi_vault
  - name: community.kubernetes
  - name: community.network
  - name: community.windows
  - name: kubernetes.core